project_name: 'experiments_1'
dataset: 'MNIST'
seed: 0
split: 'iid'
alpha: 0.5
num_clients: 2
imbalanced_ratio: 0
corruption_prob: 0
corruption_type: 'uniform'
algorithm: 'FedAvg'
model: 'ConvNet2'
optimizer: 'SGD' # Adam
use_gpu: true
epoch: 20
batch_size: 512
test_batch_size: 1024
lr: 0.01
weight_decay: 0.004
local_round: 5
num_clients_per_round: 2
watch_client: 'all'
l2_diff: True
cka: True




