project_name: 'cifar10'
dataset: 'CIFAR10'
seed: 1
split: 'iid' #niid, noisy_clients, imbalanced_clients
num_noisy_clients: 0
num_imabalanced_clients: 0
alpha: 0.5
num_clients: 10
imbalanced_ratio: 0
corruption_prob: 0
corruption_type: 'uniform'
algorithm: 'FedAvg'
model: 'ConvNet2'
optimizer: 'SGD' 
use_gpu: 'best'
epoch: 100
batch_size: 2048
test_batch_size: 2048
lr: 0.005
weight_decay: 0.004
momentum: 0.9
local_round: 5
num_clients_per_round: 3
save: False





