wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1659592062
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      4: 3.9.12
      5: 0.12.16
      8:
      - 1
      - 3
      - 5
algorithm:
  desc: null
  value: FedAvg
alpha:
  desc: null
  value: 0
batch_size:
  desc: null
  value: 128
corruption_prob:
  desc: null
  value: 0.3
dataset:
  desc: null
  value: MNIST
epoch:
  desc: null
  value: 10
imbalanced_ratio:
  desc: null
  value: 0
local_round:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.001
model:
  desc: null
  value: ConvNet2
num_clients:
  desc: null
  value: 10
num_clients_per_round:
  desc: null
  value: 5
saving_dir:
  desc: null
  value: experiments_1
split:
  desc: null
  value: iid
test_batch_size:
  desc: null
  value: 1024
use_gpu:
  desc: null
  value: true
